FROM node:alpine

WORKDIR /app

ENV CHROME_BIN=/usr/bin/google-chrome

COPY ./package.json ./
RUN npm install
RUN npm install -g @angular/cli@latest
COPY ./ ./

CMD ["ng","serve","--host", "0.0.0.0"]
